version: '3.8'
services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: ellatech
      POSTGRES_PASSWORD: ellatech
      POSTGRES_DB: ellatech_db
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    build: .
    depends_on:
      - db
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgres://ellatech:ellatech@db:5432/ellatech_db
    volumes:
      - .:/app
    command: npm run start:dev

volumes:
  db-data: